### ISSUE TITLE
Custom message is ignored

### ISSUE THREAD

**Issue by cadebward** [toddmedema/anti-addiction-chrome#1]
Hey! I was trying out your plugin and noticed the custom message setting isn't being used.

Thanks for the plugin!

**Comment by toddmedema** [comment]
Oh interesting! I'll look into this this weekend - just to make sure, did you hit "save settings"?

**Comment by cadebward** [comment]
Yes, I did! Looks like this may be the culprit https://github.com/toddmedema/anti-addiction-chrome/blob/master/js/content.js#L15

**Comment by toddmedema** [comment]
Fixed with https://github.com/toddmedema/anti-addiction-chrome/commit/12d1fb8b011d0a40dfbfcd86868faccf1e490e34

Deploying now, will take a couple of days for Google to approve
